// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/paulvollmer/robotstxt-datastore/server/ent/migrate"

	"github.com/paulvollmer/robotstxt-datastore/server/ent/robotstxt"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Robotstxt is the client for interacting with the Robotstxt builders.
	Robotstxt *RobotstxtClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Robotstxt = NewRobotstxtClient(c.config)
}

// Open opens a connection to the database specified by the driver name and a
// driver-specific data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:    cfg,
		Robotstxt: NewRobotstxtClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Robotstxt.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Robotstxt.Use(hooks...)
}

// RobotstxtClient is a client for the Robotstxt schema.
type RobotstxtClient struct {
	config
}

// NewRobotstxtClient returns a client for the Robotstxt from the given config.
func NewRobotstxtClient(c config) *RobotstxtClient {
	return &RobotstxtClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `robotstxt.Hooks(f(g(h())))`.
func (c *RobotstxtClient) Use(hooks ...Hook) {
	c.hooks.Robotstxt = append(c.hooks.Robotstxt, hooks...)
}

// Create returns a create builder for Robotstxt.
func (c *RobotstxtClient) Create() *RobotstxtCreate {
	mutation := newRobotstxtMutation(c.config, OpCreate)
	return &RobotstxtCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Robotstxt.
func (c *RobotstxtClient) Update() *RobotstxtUpdate {
	mutation := newRobotstxtMutation(c.config, OpUpdate)
	return &RobotstxtUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RobotstxtClient) UpdateOne(r *Robotstxt) *RobotstxtUpdateOne {
	return c.UpdateOneID(r.ID)
}

// UpdateOneID returns an update builder for the given id.
func (c *RobotstxtClient) UpdateOneID(id int) *RobotstxtUpdateOne {
	mutation := newRobotstxtMutation(c.config, OpUpdateOne)
	mutation.id = &id
	return &RobotstxtUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Robotstxt.
func (c *RobotstxtClient) Delete() *RobotstxtDelete {
	mutation := newRobotstxtMutation(c.config, OpDelete)
	return &RobotstxtDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RobotstxtClient) DeleteOne(r *Robotstxt) *RobotstxtDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RobotstxtClient) DeleteOneID(id int) *RobotstxtDeleteOne {
	builder := c.Delete().Where(robotstxt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RobotstxtDeleteOne{builder}
}

// Create returns a query builder for Robotstxt.
func (c *RobotstxtClient) Query() *RobotstxtQuery {
	return &RobotstxtQuery{config: c.config}
}

// Get returns a Robotstxt entity by its id.
func (c *RobotstxtClient) Get(ctx context.Context, id int) (*Robotstxt, error) {
	return c.Query().Where(robotstxt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RobotstxtClient) GetX(ctx context.Context, id int) *Robotstxt {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// Hooks returns the client hooks.
func (c *RobotstxtClient) Hooks() []Hook {
	return c.hooks.Robotstxt
}
