// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/paulvollmer/robotstxt-datastore/server/ent/robotstxt"
	"github.com/paulvollmer/robotstxt-datastore/server/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	robotstxtFields := schema.Robotstxt{}.Fields()
	_ = robotstxtFields
	// robotstxtDescCreatedAt is the schema descriptor for created_at field.
	robotstxtDescCreatedAt := robotstxtFields[0].Descriptor()
	// robotstxt.DefaultCreatedAt holds the default value on creation for the created_at field.
	robotstxt.DefaultCreatedAt = robotstxtDescCreatedAt.Default.(func() time.Time)
	// robotstxtDescUpdatedAt is the schema descriptor for updated_at field.
	robotstxtDescUpdatedAt := robotstxtFields[1].Descriptor()
	// robotstxt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	robotstxt.DefaultUpdatedAt = robotstxtDescUpdatedAt.Default.(func() time.Time)
	// robotstxt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	robotstxt.UpdateDefaultUpdatedAt = robotstxtDescUpdatedAt.UpdateDefault.(func() time.Time)
}
