// Code generated by entc, DO NOT EDIT.

package robotstxt

import (
	"time"
)

const (
	// Label holds the string label denoting the robotstxt type in the database.
	Label = "robotstxt"
	// FieldID holds the string denoting the id field in the database.
	FieldID           = "id"           // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt    = "created_at"   // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt    = "updated_at"   // FieldHost holds the string denoting the host vertex property in the database.
	FieldHost         = "host"         // FieldScheme holds the string denoting the scheme vertex property in the database.
	FieldScheme       = "scheme"       // FieldResponseURL holds the string denoting the response_url vertex property in the database.
	FieldResponseURL  = "response_url" // FieldBody holds the string denoting the body vertex property in the database.
	FieldBody         = "body"         // FieldStatuscode holds the string denoting the statuscode vertex property in the database.
	FieldStatuscode   = "statuscode"   // FieldResponseTime holds the string denoting the response_time vertex property in the database.
	FieldResponseTime = "response_time"

	// Table holds the table name of the robotstxt in the database.
	Table = "robotstxts"
)

// Columns holds all SQL columns for robotstxt fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldHost,
	FieldScheme,
	FieldResponseURL,
	FieldBody,
	FieldStatuscode,
	FieldResponseTime,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)
