// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Robotstxt is the predicate function for robotstxt builders.
type Robotstxt func(*sql.Selector)
