// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// RobotstxtsColumns holds the columns for the "robotstxts" table.
	RobotstxtsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "host", Type: field.TypeString, Unique: true},
		{Name: "scheme", Type: field.TypeString},
		{Name: "response_url", Type: field.TypeString},
		{Name: "body", Type: field.TypeBytes},
		{Name: "statuscode", Type: field.TypeInt32},
		{Name: "response_time", Type: field.TypeInt64},
	}
	// RobotstxtsTable holds the schema information for the "robotstxts" table.
	RobotstxtsTable = &schema.Table{
		Name:        "robotstxts",
		Columns:     RobotstxtsColumns,
		PrimaryKey:  []*schema.Column{RobotstxtsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RobotstxtsTable,
	}
)

func init() {
}
