// Code generated by protoc-gen-go. DO NOT EDIT.
// source: robotstxt/robotstxt.proto

package robotstxt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The available sort options
type ListRobotstxtsRequest_Sort int32

const (
	// Sort by host
	ListRobotstxtsRequest_HOST ListRobotstxtsRequest_Sort = 0
	// Sort by created_at
	ListRobotstxtsRequest_CREATED_AT ListRobotstxtsRequest_Sort = 1
	// Sort by updated_at
	ListRobotstxtsRequest_UPDATED_AT ListRobotstxtsRequest_Sort = 2
)

var ListRobotstxtsRequest_Sort_name = map[int32]string{
	0: "HOST",
	1: "CREATED_AT",
	2: "UPDATED_AT",
}
var ListRobotstxtsRequest_Sort_value = map[string]int32{
	"HOST":       0,
	"CREATED_AT": 1,
	"UPDATED_AT": 2,
}

func (x ListRobotstxtsRequest_Sort) String() string {
	return proto.EnumName(ListRobotstxtsRequest_Sort_name, int32(x))
}
func (ListRobotstxtsRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{4, 0}
}

// The available order options
type ListRobotstxtsRequest_Order int32

const (
	// Order by asc
	ListRobotstxtsRequest_ASC ListRobotstxtsRequest_Order = 0
	// Order by desc
	ListRobotstxtsRequest_DESC ListRobotstxtsRequest_Order = 1
)

var ListRobotstxtsRequest_Order_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var ListRobotstxtsRequest_Order_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListRobotstxtsRequest_Order) String() string {
	return proto.EnumName(ListRobotstxtsRequest_Order_name, int32(x))
}
func (ListRobotstxtsRequest_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{4, 1}
}

// Option to set the uri, refresh and sitemap request rpc call.
type Check struct {
	// The host of the robots.txt source.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Set to true to request the robots.txt data and update the database.
	Refresh bool `protobuf:"varint,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	// If refresh is true and refresh_after is not 0, then the rpc will decide if a request will be send to the uri.
	RefreshAfter         int32    `protobuf:"varint,3,opt,name=refresh_after,json=refreshAfter,proto3" json:"refresh_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{0}
}
func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (dst *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(dst, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Check) GetRefresh() bool {
	if m != nil {
		return m.Refresh
	}
	return false
}

func (m *Check) GetRefreshAfter() int32 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

type Robotstxt struct {
	//  The creation date
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The update date
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The host is used at the Check rpc to send the request to the server.
	// The full request URL is build by the default scheme + host + /robots.txt
	// (for example google.com will become https://google.com/robots.txt).
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// The scheme
	Scheme string `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// The server response status code
	Statuscode int32 `protobuf:"varint,5,opt,name=statuscode,proto3" json:"statuscode,omitempty"`
	// The server response URL
	ResponseUrl string `protobuf:"bytes,6,opt,name=response_url,json=responseUrl,proto3" json:"response_url,omitempty"`
	// The server response time
	ResponseTime int64 `protobuf:"varint,7,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	// The server response body
	Robotstxt string `protobuf:"bytes,8,opt,name=robotstxt,proto3" json:"robotstxt,omitempty"`
	// The robots.txt rules array
	Rules []*Rule `protobuf:"bytes,9,rep,name=rules,proto3" json:"rules,omitempty"`
	// The robots.txt sitemaps string array
	Sitemaps             []string `protobuf:"bytes,10,rep,name=sitemaps,proto3" json:"sitemaps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Robotstxt) Reset()         { *m = Robotstxt{} }
func (m *Robotstxt) String() string { return proto.CompactTextString(m) }
func (*Robotstxt) ProtoMessage()    {}
func (*Robotstxt) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{1}
}
func (m *Robotstxt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robotstxt.Unmarshal(m, b)
}
func (m *Robotstxt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robotstxt.Marshal(b, m, deterministic)
}
func (dst *Robotstxt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robotstxt.Merge(dst, src)
}
func (m *Robotstxt) XXX_Size() int {
	return xxx_messageInfo_Robotstxt.Size(m)
}
func (m *Robotstxt) XXX_DiscardUnknown() {
	xxx_messageInfo_Robotstxt.DiscardUnknown(m)
}

var xxx_messageInfo_Robotstxt proto.InternalMessageInfo

func (m *Robotstxt) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Robotstxt) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Robotstxt) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Robotstxt) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *Robotstxt) GetStatuscode() int32 {
	if m != nil {
		return m.Statuscode
	}
	return 0
}

func (m *Robotstxt) GetResponseUrl() string {
	if m != nil {
		return m.ResponseUrl
	}
	return ""
}

func (m *Robotstxt) GetResponseTime() int64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

func (m *Robotstxt) GetRobotstxt() string {
	if m != nil {
		return m.Robotstxt
	}
	return ""
}

func (m *Robotstxt) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Robotstxt) GetSitemaps() []string {
	if m != nil {
		return m.Sitemaps
	}
	return nil
}

type Rule struct {
	// The User-Agent
	Agent string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	//  The array of paths
	Paths                []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{2}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *Rule) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type ListRobotstxtsResponse struct {
	// The total number of items at the database.
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// The list of items to return.
	Items                []*Robotstxt `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListRobotstxtsResponse) Reset()         { *m = ListRobotstxtsResponse{} }
func (m *ListRobotstxtsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRobotstxtsResponse) ProtoMessage()    {}
func (*ListRobotstxtsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{3}
}
func (m *ListRobotstxtsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRobotstxtsResponse.Unmarshal(m, b)
}
func (m *ListRobotstxtsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRobotstxtsResponse.Marshal(b, m, deterministic)
}
func (dst *ListRobotstxtsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRobotstxtsResponse.Merge(dst, src)
}
func (m *ListRobotstxtsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRobotstxtsResponse.Size(m)
}
func (m *ListRobotstxtsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRobotstxtsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRobotstxtsResponse proto.InternalMessageInfo

func (m *ListRobotstxtsResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListRobotstxtsResponse) GetItems() []*Robotstxt {
	if m != nil {
		return m.Items
	}
	return nil
}

// Options to control the number of items and the offset.
type ListRobotstxtsRequest struct {
	// Limit the number of array items.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Request offset.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Search for host(s).
	Search               string                      `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SortBy               ListRobotstxtsRequest_Sort  `protobuf:"varint,5,opt,name=sort_by,json=sortBy,proto3,enum=grpc.robotstxt.v1.ListRobotstxtsRequest_Sort" json:"sort_by,omitempty"`
	OrderBy              ListRobotstxtsRequest_Order `protobuf:"varint,6,opt,name=order_by,json=orderBy,proto3,enum=grpc.robotstxt.v1.ListRobotstxtsRequest_Order" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListRobotstxtsRequest) Reset()         { *m = ListRobotstxtsRequest{} }
func (m *ListRobotstxtsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRobotstxtsRequest) ProtoMessage()    {}
func (*ListRobotstxtsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{4}
}
func (m *ListRobotstxtsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRobotstxtsRequest.Unmarshal(m, b)
}
func (m *ListRobotstxtsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRobotstxtsRequest.Marshal(b, m, deterministic)
}
func (dst *ListRobotstxtsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRobotstxtsRequest.Merge(dst, src)
}
func (m *ListRobotstxtsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRobotstxtsRequest.Size(m)
}
func (m *ListRobotstxtsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRobotstxtsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRobotstxtsRequest proto.InternalMessageInfo

func (m *ListRobotstxtsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRobotstxtsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRobotstxtsRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *ListRobotstxtsRequest) GetSortBy() ListRobotstxtsRequest_Sort {
	if m != nil {
		return m.SortBy
	}
	return ListRobotstxtsRequest_HOST
}

func (m *ListRobotstxtsRequest) GetOrderBy() ListRobotstxtsRequest_Order {
	if m != nil {
		return m.OrderBy
	}
	return ListRobotstxtsRequest_ASC
}

type GetRobotstxtRequest struct {
	// The host of the robots.txt source.
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRobotstxtRequest) Reset()         { *m = GetRobotstxtRequest{} }
func (m *GetRobotstxtRequest) String() string { return proto.CompactTextString(m) }
func (*GetRobotstxtRequest) ProtoMessage()    {}
func (*GetRobotstxtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotstxt_15be4eee54d38b93, []int{5}
}
func (m *GetRobotstxtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRobotstxtRequest.Unmarshal(m, b)
}
func (m *GetRobotstxtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRobotstxtRequest.Marshal(b, m, deterministic)
}
func (dst *GetRobotstxtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRobotstxtRequest.Merge(dst, src)
}
func (m *GetRobotstxtRequest) XXX_Size() int {
	return xxx_messageInfo_GetRobotstxtRequest.Size(m)
}
func (m *GetRobotstxtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRobotstxtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRobotstxtRequest proto.InternalMessageInfo

func (m *GetRobotstxtRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*Check)(nil), "grpc.robotstxt.v1.Check")
	proto.RegisterType((*Robotstxt)(nil), "grpc.robotstxt.v1.Robotstxt")
	proto.RegisterType((*Rule)(nil), "grpc.robotstxt.v1.Rule")
	proto.RegisterType((*ListRobotstxtsResponse)(nil), "grpc.robotstxt.v1.ListRobotstxtsResponse")
	proto.RegisterType((*ListRobotstxtsRequest)(nil), "grpc.robotstxt.v1.ListRobotstxtsRequest")
	proto.RegisterType((*GetRobotstxtRequest)(nil), "grpc.robotstxt.v1.GetRobotstxtRequest")
	proto.RegisterEnum("grpc.robotstxt.v1.ListRobotstxtsRequest_Sort", ListRobotstxtsRequest_Sort_name, ListRobotstxtsRequest_Sort_value)
	proto.RegisterEnum("grpc.robotstxt.v1.ListRobotstxtsRequest_Order", ListRobotstxtsRequest_Order_name, ListRobotstxtsRequest_Order_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RobotstxtServiceClient is the client API for RobotstxtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RobotstxtServiceClient interface {
	// Check if a robots.txt source exists or is outdated.
	CheckRobotstxt(ctx context.Context, in *Check, opts ...grpc.CallOption) (*Robotstxt, error)
	// List robots.txt sources.
	ListRobotstxts(ctx context.Context, in *ListRobotstxtsRequest, opts ...grpc.CallOption) (*ListRobotstxtsResponse, error)
	// Gets a robots.txt source.
	GetRobotstxt(ctx context.Context, in *GetRobotstxtRequest, opts ...grpc.CallOption) (*Robotstxt, error)
}

type robotstxtServiceClient struct {
	cc *grpc.ClientConn
}

func NewRobotstxtServiceClient(cc *grpc.ClientConn) RobotstxtServiceClient {
	return &robotstxtServiceClient{cc}
}

func (c *robotstxtServiceClient) CheckRobotstxt(ctx context.Context, in *Check, opts ...grpc.CallOption) (*Robotstxt, error) {
	out := new(Robotstxt)
	err := c.cc.Invoke(ctx, "/grpc.robotstxt.v1.RobotstxtService/CheckRobotstxt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotstxtServiceClient) ListRobotstxts(ctx context.Context, in *ListRobotstxtsRequest, opts ...grpc.CallOption) (*ListRobotstxtsResponse, error) {
	out := new(ListRobotstxtsResponse)
	err := c.cc.Invoke(ctx, "/grpc.robotstxt.v1.RobotstxtService/ListRobotstxts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotstxtServiceClient) GetRobotstxt(ctx context.Context, in *GetRobotstxtRequest, opts ...grpc.CallOption) (*Robotstxt, error) {
	out := new(Robotstxt)
	err := c.cc.Invoke(ctx, "/grpc.robotstxt.v1.RobotstxtService/GetRobotstxt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotstxtServiceServer is the server API for RobotstxtService service.
type RobotstxtServiceServer interface {
	// Check if a robots.txt source exists or is outdated.
	CheckRobotstxt(context.Context, *Check) (*Robotstxt, error)
	// List robots.txt sources.
	ListRobotstxts(context.Context, *ListRobotstxtsRequest) (*ListRobotstxtsResponse, error)
	// Gets a robots.txt source.
	GetRobotstxt(context.Context, *GetRobotstxtRequest) (*Robotstxt, error)
}

func RegisterRobotstxtServiceServer(s *grpc.Server, srv RobotstxtServiceServer) {
	s.RegisterService(&_RobotstxtService_serviceDesc, srv)
}

func _RobotstxtService_CheckRobotstxt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Check)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotstxtServiceServer).CheckRobotstxt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.robotstxt.v1.RobotstxtService/CheckRobotstxt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotstxtServiceServer).CheckRobotstxt(ctx, req.(*Check))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotstxtService_ListRobotstxts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRobotstxtsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotstxtServiceServer).ListRobotstxts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.robotstxt.v1.RobotstxtService/ListRobotstxts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotstxtServiceServer).ListRobotstxts(ctx, req.(*ListRobotstxtsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotstxtService_GetRobotstxt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRobotstxtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotstxtServiceServer).GetRobotstxt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.robotstxt.v1.RobotstxtService/GetRobotstxt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotstxtServiceServer).GetRobotstxt(ctx, req.(*GetRobotstxtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RobotstxtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.robotstxt.v1.RobotstxtService",
	HandlerType: (*RobotstxtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRobotstxt",
			Handler:    _RobotstxtService_CheckRobotstxt_Handler,
		},
		{
			MethodName: "ListRobotstxts",
			Handler:    _RobotstxtService_ListRobotstxts_Handler,
		},
		{
			MethodName: "GetRobotstxt",
			Handler:    _RobotstxtService_GetRobotstxt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "robotstxt/robotstxt.proto",
}

func init() {
	proto.RegisterFile("robotstxt/robotstxt.proto", fileDescriptor_robotstxt_15be4eee54d38b93)
}

var fileDescriptor_robotstxt_15be4eee54d38b93 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x6d, 0xec, 0x38, 0x3f, 0x37, 0xfd, 0xa2, 0x7c, 0x03, 0x94, 0x21, 0xaa, 0x68, 0x30, 0x12,
	0x72, 0x17, 0x75, 0xc1, 0xac, 0x58, 0xa6, 0x69, 0xa1, 0x48, 0x48, 0x45, 0x93, 0x74, 0xd3, 0x4d,
	0xe4, 0x38, 0x37, 0x3f, 0xc2, 0xe9, 0x98, 0x99, 0x71, 0x45, 0x1f, 0x85, 0x97, 0xe1, 0xd1, 0x10,
	0x9a, 0xf1, 0x4f, 0x0a, 0x58, 0xa5, 0xbb, 0x39, 0x47, 0xe7, 0xdc, 0x39, 0xf7, 0x5e, 0x8f, 0xe1,
	0x99, 0xe0, 0x33, 0xae, 0xa4, 0xfa, 0xa6, 0x8e, 0xcb, 0x93, 0x9f, 0x08, 0xae, 0x38, 0xf9, 0x7f,
	0x29, 0x92, 0xc8, 0xdf, 0xb2, 0x37, 0x6f, 0xfa, 0x07, 0x4b, 0xce, 0x97, 0x31, 0x1e, 0x1b, 0xc1,
	0x2c, 0x5d, 0x1c, 0xab, 0xf5, 0x06, 0xa5, 0x0a, 0x37, 0x49, 0xe6, 0x71, 0xaf, 0xc0, 0x19, 0xad,
	0x30, 0xfa, 0x42, 0x08, 0xd4, 0x57, 0x5c, 0x2a, 0x5a, 0x1b, 0xd4, 0xbc, 0x36, 0x33, 0x67, 0x42,
	0xa1, 0x29, 0x70, 0x21, 0x50, 0xae, 0xa8, 0x35, 0xa8, 0x79, 0x2d, 0x56, 0x40, 0xf2, 0x12, 0xfe,
	0xcb, 0x8f, 0xd3, 0x70, 0xa1, 0x50, 0x50, 0x7b, 0x50, 0xf3, 0x1c, 0xb6, 0x9b, 0x93, 0x43, 0xcd,
	0xb9, 0x3f, 0x2d, 0x68, 0xb3, 0x22, 0x0d, 0x79, 0x07, 0x10, 0x09, 0x0c, 0x15, 0xce, 0xa7, 0x61,
	0x76, 0x4d, 0x27, 0xe8, 0xfb, 0x59, 0x3e, 0xbf, 0xc8, 0xe7, 0x4f, 0x8a, 0x7c, 0xac, 0x9d, 0xab,
	0x87, 0xc6, 0x9a, 0x26, 0xf3, 0xc2, 0x6a, 0xfd, 0xdb, 0x9a, 0xab, 0x87, 0xaa, 0x6c, 0xcb, 0xbe,
	0xd3, 0xd6, 0x1e, 0x34, 0x64, 0xb4, 0xc2, 0x0d, 0xd2, 0xba, 0x61, 0x73, 0x44, 0x9e, 0x03, 0x48,
	0x15, 0xaa, 0x54, 0x46, 0x7c, 0x8e, 0xd4, 0x31, 0x1d, 0xdd, 0x61, 0xc8, 0x0b, 0xd8, 0x15, 0x28,
	0x13, 0x7e, 0x2d, 0x71, 0x9a, 0x8a, 0x98, 0x36, 0x8c, 0xbb, 0x53, 0x70, 0x97, 0x22, 0xce, 0xe6,
	0x92, 0x4b, 0xf4, 0xa8, 0x69, 0x73, 0x50, 0xf3, 0x6c, 0x56, 0xfa, 0x74, 0x46, 0xb2, 0x0f, 0xed,
	0x72, 0x49, 0xb4, 0x65, 0x8a, 0x6c, 0x09, 0x72, 0x04, 0x8e, 0x48, 0x63, 0x94, 0xb4, 0x3d, 0xb0,
	0xbd, 0x4e, 0xf0, 0xd4, 0xff, 0x6b, 0xab, 0x3e, 0x4b, 0x63, 0x64, 0x99, 0x8a, 0xf4, 0xa1, 0x25,
	0xd7, 0x0a, 0x37, 0x61, 0x22, 0x29, 0x0c, 0x6c, 0xaf, 0xcd, 0x4a, 0xec, 0x06, 0x50, 0xd7, 0x52,
	0xf2, 0x18, 0x9c, 0x70, 0x89, 0xd7, 0xc5, 0x72, 0x33, 0xa0, 0xd9, 0x24, 0x54, 0x2b, 0x49, 0x2d,
	0x63, 0xcb, 0x80, 0xbb, 0x81, 0xbd, 0x4f, 0x6b, 0xa9, 0xca, 0xbd, 0x49, 0x96, 0x47, 0x27, 0x07,
	0xd0, 0x51, 0x5c, 0x85, 0xf1, 0x34, 0xe2, 0x69, 0x5e, 0xcb, 0x66, 0x60, 0xa8, 0x91, 0x66, 0x48,
	0x00, 0x8e, 0xbe, 0x39, 0x2b, 0xd8, 0x09, 0xf6, 0xab, 0x92, 0x17, 0x80, 0x65, 0x52, 0xf7, 0x87,
	0x05, 0x4f, 0xfe, 0xbc, 0xef, 0x6b, 0x8a, 0xd2, 0xc4, 0x8b, 0xd7, 0x9b, 0x75, 0x76, 0x91, 0xc3,
	0x32, 0xa0, 0x77, 0xc7, 0x17, 0x0b, 0x89, 0xd9, 0x67, 0x60, 0xb3, 0x1c, 0x99, 0x9d, 0x62, 0x28,
	0xa2, 0x55, 0xb9, 0x53, 0x83, 0xc8, 0x7b, 0x68, 0x4a, 0x2e, 0xd4, 0x74, 0x76, 0x6b, 0x16, 0xda,
	0x0d, 0x8e, 0x2a, 0x52, 0x55, 0x06, 0xf0, 0xc7, 0x5c, 0x28, 0xd6, 0xd0, 0xee, 0x93, 0x5b, 0xf2,
	0x11, 0x5a, 0x5c, 0xcc, 0x51, 0xe8, 0x42, 0x0d, 0x53, 0xc8, 0x7f, 0x70, 0xa1, 0x0b, 0x6d, 0x64,
	0x4d, 0xe3, 0x3f, 0xb9, 0x75, 0x5f, 0x43, 0x5d, 0x97, 0x26, 0x2d, 0xa8, 0x9f, 0x5f, 0x8c, 0x27,
	0xbd, 0x1d, 0xd2, 0x05, 0x18, 0xb1, 0xb3, 0xe1, 0xe4, 0xec, 0x74, 0x3a, 0x9c, 0xf4, 0x6a, 0x1a,
	0x5f, 0x7e, 0x3e, 0x2d, 0xb0, 0xe5, 0xf6, 0xc1, 0x31, 0x35, 0x48, 0x13, 0xec, 0xe1, 0x78, 0xd4,
	0xdb, 0xd1, 0xde, 0xd3, 0xb3, 0xf1, 0xa8, 0x57, 0x73, 0x0f, 0xe1, 0xd1, 0x07, 0xdc, 0x5e, 0x5a,
	0x4c, 0xaf, 0xe2, 0x39, 0x07, 0xdf, 0x2d, 0xe8, 0x95, 0xc2, 0x31, 0x8a, 0x9b, 0x75, 0x84, 0xe4,
	0x1c, 0xba, 0xe6, 0x07, 0xb0, 0x7d, 0xa8, 0xb4, 0xa2, 0x31, 0x23, 0xe9, 0xdf, 0xbb, 0x51, 0x82,
	0xd0, 0xfd, 0xbd, 0x7f, 0xe2, 0x3d, 0x74, 0x44, 0xfd, 0xc3, 0x07, 0x28, 0xf3, 0xcf, 0x70, 0x02,
	0xbb, 0x77, 0x1b, 0x26, 0xaf, 0x2a, 0xac, 0x15, 0x13, 0xb9, 0x3f, 0xfc, 0x49, 0xe7, 0x6a, 0xfb,
	0x04, 0x67, 0x0d, 0xf3, 0x4f, 0x79, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x6d, 0x93, 0x68,
	0x6c, 0x05, 0x00, 0x00,
}
